export const countries = [
  { label: "India", key: "India" },
  { label: "Afghanistan", key: "Afghanistan" },
  { label: "Åland Islands", key: "Åland Islands" },
  { label: "Albania", key: "Albania" },
  { label: "Algeria", key: "Algeria" },
  { label: "American Samoa", key: "American Samoa" },
  { label: "AndorrA", key: "AndorrA" },
  { label: "Angola", key: "Angola" },
  { label: "Anguilla", key: "Anguilla" },
  { label: "Antarctica", key: "Antarctica" },
  { label: "Antigua and Barbuda", key: "Antigua and Barbuda" },
  { label: "Argentina", key: "Argentina" },
  { label: "Armenia", key: "Armenia" },
  { label: "Aruba", key: "Aruba" },
  { label: "Australia", key: "Australia" },
  { label: "Austria", key: "Austria" },
  { label: "Azerbaijan", key: "Azerbaijan" },
  { label: "Bahamas", key: "Bahamas" },
  { label: "Bahrain", key: "Bahrain" },
  { label: "Bangladesh", key: "Bangladesh" },
  { label: "Barbados", key: "Barbados" },
  { label: "Belarus", key: "Belarus" },
  { label: "Belgium", key: "Belgium" },
  { label: "Belize", key: "Belize" },
  { label: "Benin", key: "Benin" },
  { label: "Bermuda", key: "Bermuda" },
  { label: "Bhutan", key: "Bhutan" },
  { label: "Bolivia", key: "Bolivia" },
  { label: "Bosnia and Herzegovina", key: "Bosnia and Herzegovina" },
  { label: "Botswana", key: "Botswana" },
  { label: "Bouvet Island", key: "Bouvet Island" },
  { label: "Brazil", key: "Brazil" },
  {
    label: "British Indian Ocean Territory",
    key: "British Indian Ocean Territory",
  },
  { label: "Brunei Darussalam", key: "Brunei Darussalam" },
  { label: "Bulgaria", key: "Bulgaria" },
  { label: "Burkina Faso", key: "Burkina Faso" },
  { label: "Burundi", key: "Burundi" },
  { label: "Cambodia", key: "Cambodia" },
  { label: "Cameroon", key: "Cameroon" },
  { label: "Canada", key: "Canada" },
  { label: "Cape Verde", key: "Cape Verde" },
  { label: "Cayman Islands", key: "Cayman Islands" },
  { label: "Central African Republic", key: "Central African Republic" },
  { label: "Chad", key: "Chad" },
  { label: "Chile", key: "Chile" },
  { label: "China", key: "China" },
  { label: "Christmas Island", key: "Christmas Island" },
  { label: "Cocos (Keeling) Islands", key: "Cocos (Keeling) Islands" },
  { label: "Colombia", key: "Colombia" },
  { label: "Comoros", key: "Comoros" },
  { label: "Congo", key: "Congo" },
  { label: "Congo, The Democratic Republic of the", key: "CD" },
  { label: "Cook Islands", key: "Cook Islands" },
  { label: "Costa Rica", key: "Costa Rica" },
  { label: "Cote D'Ivoire", key: "Cote D'Ivoire" },
  { label: "Croatia", key: "Croatia" },
  { label: "Cuba", key: "Cuba" },
  { label: "Cyprus", key: "Cyprus" },
  { label: "Czech Republic", key: "Czech Republic" },
  { label: "Denmark", key: "Denmark" },
  { label: "Djibouti", key: "Djibouti" },
  { label: "Dominica", key: "Dominica" },
  { label: "Dominican Republic", key: "Dominican Republic" },
  { label: "Ecuador", key: "Ecuador" },
  { label: "Egypt", key: "Egypt" },
  { label: "El Salvador", key: "El Salvador" },
  { label: "Equatorial Guinea", key: "Equatorial Guinea" },
  { label: "Eritrea", key: "Eritrea" },
  { label: "Estonia", key: "Estonia" },
  { label: "Ethiopia", key: "Ethiopia" },
  { label: "Falkland Islands (Malvinas)", key: "Falkland Islands (Malvinas)" },
  { label: "Faroe Islands", key: "Faroe Islands" },
  { label: "Fiji", key: "Fiji" },
  { label: "Finland", key: "Finland" },
  { label: "France", key: "France" },
  { label: "French Guiana", key: "French Guiana" },
  { label: "French Polynesia", key: "French Polynesia" },
  { label: "French Southern Territories", key: "French Southern Territories" },
  { label: "Gabon", key: "Gabon" },
  { label: "Gambia", key: "Gambia" },
  { label: "Georgia", key: "Georgia" },
  { label: "Germany", key: "Germany" },
  { label: "Ghana", key: "Ghana" },
  { label: "Gibraltar", key: "Gibraltar" },
  { label: "Greece", key: "Greece" },
  { label: "Greenland", key: "Greenland" },
  { label: "Grenada", key: "Grenada" },
  { label: "Guadeloupe", key: "Guadeloupe" },
  { label: "Guam", key: "Guam" },
  { label: "Guatemala", key: "Guatemala" },
  { label: "Guernsey", key: "Guernsey" },
  { label: "Guinea", key: "Guinea" },
  { label: "Guinea-Bissau", key: "Guinea-Bissau" },
  { label: "Guyana", key: "Guyana" },
  { label: "Haiti", key: "Haiti" },
  {
    label: "Heard Island and Mcdonald Islands",
    key: "Heard Island and Mcdonald Islands",
  },
  { label: "Holy See (Vatican City State)", key: "VA" },
  { label: "Honduras", key: "Honduras" },
  { label: "Hong Kong", key: "Hong Kong" },
  { label: "Hungary", key: "Hungary" },
  { label: "Iceland", key: "Iceland" },
  { label: "Indonesia", key: "Indonesia" },
  { label: "Iran, Islamic Republic Of", key: "Iran, Islamic Republic Of" },
  { label: "Iraq", key: "Iraq" },
  { label: "Ireland", key: "Ireland" },
  { label: "Isle of Man", key: "Isle of Man" },
  { label: "Israel", key: "Israel" },
  { label: "Italy", key: "Italy" },
  { label: "Jamaica", key: "Jamaica" },
  { label: "Japan", key: "Japan" },
  { label: "Jersey", key: "Jersey" },
  { label: "Jordan", key: "Jordan" },
  { label: "Kazakhstan", key: "Kazakhstan" },
  { label: "Kenya", key: "Kenya" },
  { label: "Kiribati", key: "Kiribati" },
  { label: "Korea, Democratic People'S Republic of", key: "KP" },
  { label: "Korea, Republic of", key: "Korea, Republic of" },
  { label: "Kuwait", key: "Kuwait" },
  { label: "Kyrgyzstan", key: "Kyrgyzstan" },
  { label: "Lao People'S Democratic Republic", key: "LA" },
  { label: "Latvia", key: "Latvia" },
  { label: "Lebanon", key: "Lebanon" },
  { label: "Lesotho", key: "Lesotho" },
  { label: "Liberia", key: "Liberia" },
  { label: "Libyan Arab Jamahiriya", key: "Libyan Arab Jamahiriya" },
  { label: "Liechtenstein", key: "Liechtenstein" },
  { label: "Lithuania", key: "Lithuania" },
  { label: "Luxembourg", key: "Luxembourg" },
  { label: "Macao", key: "Macao" },
  { label: "Macedonia, The Former Yugoslav Republic of", key: "MK" },
  { label: "Madagascar", key: "Madagascar" },
  { label: "Malawi", key: "Malawi" },
  { label: "Malaysia", key: "Malaysia" },
  { label: "Maldives", key: "Maldives" },
  { label: "Mali", key: "Mali" },
  { label: "Malta", key: "Malta" },
  { label: "Marshall Islands", key: "Marshall Islands" },
  { label: "Martinique", key: "Martinique" },
  { label: "Mauritania", key: "Mauritania" },
  { label: "Mauritius", key: "Mauritius" },
  { label: "Mayotte", key: "Mayotte" },
  { label: "Mexico", key: "Mexico" },
  {
    label: "Micronesia, Federated States of",
    key: "Micronesia, Federated States of",
  },
  { label: "Moldova, Republic of", key: "Moldova, Republic of" },
  { label: "Monaco", key: "Monaco" },
  { label: "Mongolia", key: "Mongolia" },
  { label: "Montserrat", key: "Montserrat" },
  { label: "Morocco", key: "Morocco" },
  { label: "Mozambique", key: "Mozambique" },
  { label: "Myanmar", key: "Myanmar" },
  { label: "Namibia", key: "Namibia" },
  { label: "Nauru", key: "Nauru" },
  { label: "Nepal", key: "Nepal" },
  { label: "Netherlands", key: "Netherlands" },
  { label: "Netherlands Antilles", key: "Netherlands Antilles" },
  { label: "New Caledonia", key: "New Caledonia" },
  { label: "New Zealand", key: "New Zealand" },
  { label: "Nicaragua", key: "Nicaragua" },
  { label: "Niger", key: "Niger" },
  { label: "Nigeria", key: "Nigeria" },
  { label: "Niue", key: "Niue" },
  { label: "Norfolk Island", key: "Norfolk Island" },
  { label: "Northern Mariana Islands", key: "Northern Mariana Islands" },
  { label: "Norway", key: "Norway" },
  { label: "Oman", key: "Oman" },
  { label: "Pakistan", key: "Pakistan" },
  { label: "Palau", key: "Palau" },
  {
    label: "Palestinian Territory, Occupied",
    key: "Palestinian Territory, Occupied",
  },
  { label: "Panama", key: "Panama" },
  { label: "Papua New Guinea", key: "Papua New Guinea" },
  { label: "Paraguay", key: "Paraguay" },
  { label: "Peru", key: "Peru" },
  { label: "Philippines", key: "Philippines" },
  { label: "Pitcairn", key: "Pitcairn" },
  { label: "Poland", key: "Poland" },
  { label: "Portugal", key: "Portugal" },
  { label: "Puerto Rico", key: "Puerto Rico" },
  { label: "Qatar", key: "Qatar" },
  { label: "Reunion", key: "Reunion" },
  { label: "Romania", key: "Romania" },
  { label: "Russian Federation", key: "Russian Federation" },
  { label: "RWANDA", key: "RWANDA" },
  { label: "Saint Helena", key: "Saint Helena" },
  { label: "Saint Kitts and Nevis", key: "Saint Kitts and Nevis" },
  { label: "Saint Lucia", key: "Saint Lucia" },
  { label: "Saint Pierre and Miquelon", key: "Saint Pierre and Miquelon" },
  {
    label: "Saint Vincent and the Grenadines",
    key: "Saint Vincent and the Grenadines",
  },
  { label: "Samoa", key: "Samoa" },
  { label: "San Marino", key: "San Marino" },
  { label: "Sao Tome and Principe", key: "Sao Tome and Principe" },
  { label: "Saudi Arabia", key: "Saudi Arabia" },
  { label: "Senegal", key: "Senegal" },
  { label: "Serbia and Montenegro", key: "Serbia and Montenegro" },
  { label: "Seychelles", key: "Seychelles" },
  { label: "Sierra Leone", key: "Sierra Leone" },
  { label: "Singapore", key: "Singapore" },
  { label: "Slovakia", key: "Slovakia" },
  { label: "Slovenia", key: "Slovenia" },
  { label: "Solomon Islands", key: "Solomon Islands" },
  { label: "Somalia", key: "Somalia" },
  { label: "South Africa", key: "South Africa" },
  { label: "South Georgia and the South Sandwich Islands", key: "GS" },
  { label: "Spain", key: "Spain" },
  { label: "Sri Lanka", key: "Sri Lanka" },
  { label: "Sudan", key: "Sudan" },
  { label: "Suriname", key: "Suriname" },
  { label: "Svalbard and Jan Mayen", key: "Svalbard and Jan Mayen" },
  { label: "Swaziland", key: "Swaziland" },
  { label: "Sweden", key: "Sweden" },
  { label: "Switzerland", key: "Switzerland" },
  { label: "Syrian Arab Republic", key: "Syrian Arab Republic" },
  { label: "Taiwan, Province of China", key: "Taiwan, Province of China" },
  { label: "Tajikistan", key: "Tajikistan" },
  {
    label: "Tanzania, United Republic of",
    key: "Tanzania, United Republic of",
  },
  { label: "Thailand", key: "Thailand" },
  { label: "Timor-Leste", key: "Timor-Leste" },
  { label: "Togo", key: "Togo" },
  { label: "Tokelau", key: "Tokelau" },
  { label: "Tonga", key: "Tonga" },
  { label: "Trinidad and Tobago", key: "Trinidad and Tobago" },
  { label: "Tunisia", key: "Tunisia" },
  { label: "Turkey", key: "Turkey" },
  { label: "Turkmenistan", key: "Turkmenistan" },
  { label: "Turks and Caicos Islands", key: "Turks and Caicos Islands" },
  { label: "Tuvalu", key: "Tuvalu" },
  { label: "Uganda", key: "Uganda" },
  { label: "Ukraine", key: "Ukraine" },
  { label: "United Arab Emirates", key: "United Arab Emirates" },
  { label: "United Kingdom", key: "United Kingdom" },
  { label: "United States", key: "United States" },
  { label: "Uruguay", key: "Uruguay" },
  { label: "Uzbekistan", key: "Uzbekistan" },
  { label: "Vanuatu", key: "Vanuatu" },
  { label: "Venezuela", key: "Venezuela" },
  { label: "Viet Nam", key: "Viet Nam" },
  { label: "Virgin Islands, British", key: "Virgin Islands, British" },
  { label: "Virgin Islands, U.S.", key: "Virgin Islands, U.S." },
  { label: "Wallis and Futuna", key: "Wallis and Futuna" },
  { label: "Western Sahara", key: "Western Sahara" },
  { label: "Yemen", key: "Yemen" },
  { label: "Zambia", key: "Zambia" },
  { label: "Zimbabwe", key: "Zimbabwe" },
];
