export const romanToNumeral: { [key: string]: string } = {
  " I Year I ": " 1-1 ",
  " I Year II ": " 1-2 ",
  " II Year I ": " 2-1 ",
  " II Year II ": " 2-2 ",
  " III Year I ": " 3-1 ",
  " III Year II ": " 3-2 ",
  " IV Year I ": " 4-1 ",
  " IV Year II ": " 4-2 ",
  " I ": " 1st ",
  " II ": " 2nd",
  " III ": " 3rd ",
  " IV ": " 4th ",
  " V ": " 5th ",
  " VI ": " 6th ",
  " VII ": " 7th ",
  " VIII ": " 8th ",
  " IX ": " 9th ",
  " X ": " 10th ",
};
