const colleges =
{
    "8P": "A A R Mahaveer Engineering College",
    "9G": "AARUSHI GROUP OF INSTITUTIONS",
    "AG": "ACE Engineering College",
    "DN": "ADUSUMILLI VIJAYA COLLEGE OF ENGINEERING & RESEARCH CENTRE",
    "5G": "ADUSUMILLI VIJAYA INSTITUTE OF TECHNOLOGY & RESEARCH CENTRE",
    "H1": "AL HABEEB COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "VN": "ALEXANDER COLLEGE",
    "FG": "AMR Institute Of Technology",
    "5Q": "ANASUYA DEVI INSTITUTE OF TECHNOLOGY & SCIENCES",
    "C1": "ANURAG ENGINEERING COLLEGE",
    "Z1": "ANURAG PHARMACY COLLEGE",
    "S6": "ANWARUL ULOOM COLLEGE OF PHARMACY",
    "5R": "APEX ENGINEERING COLLEGE",
    "VP": "APOORVA INSTITUTE OF MANAGEMENT & SCIENCES",
    "W8": "ARJUN COLLEGE OF TECHNOLOGY & SCEINCES",
    "7N": "ARVINDAKSHA EDUCATIONAL SOCIETY'S GROUP OF INSTITUTIONS",
    "XQ": "ASHOKA BUSINESS SCHOOL",
    "5T": "ASHOKA Institute of Engineering & Technology",
    "H2": "ASIFIA COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "6Z": "AUROBINDO INSTITUTE OF ENGINEERING AND TECHNOLOGY",
    "XR": "AURORA'S PHARMACY COLLEGE",
    "XT": "AURORA'S PHARMACY INSTITUTE",
    "D9": "AURORA'S SCIENTIFIC, TECHNOLOGICAL AND RESEARCH ACADEMY",
    "TI": "AURORA'S TECHNOLOGICAL INSTITUTE",
    "U7": "AURORA`S TECHNOLOGICAL INSTITUTE",
    "9K": "AURORA’S TECHNOLOGICAL & MANAGEMENT ACADEMY",
    "Q6": "AVANTHI INSTITUTE OF ENGINEERING & TECHNOLOGY",
    "GN": "AVANTHI INSTITUTE OF PHARMACEUTICAL SCIENCES",
    "1Q": "AVANTHI'S P.G & RESERACH ACADEMY",
    "PT": "AVANTHI'S SCIENTIFIC TECHNOLOGICAL & RESEARCH ACADEMY",
    "5U": "AVN INSTITUTE OF ENGINEERING AND TECHNOLOGY",
    "TG": "AWARE MADHAVANJI COLLEGE OF ENGINEERING",
    "Q8": "AZAD COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "EK": "Abdul Kalam Institute of Technological Sciences",
    "J1": "Abhinav Hi-Tech College of Engineering (formerly Hi-Tech College of Engineering & Technology)",
    "65": "Adam's Engg College",
    "79": "Aizza College of Engg & Tech",
    "N1": "Amina Institute of Thechnology",
    "7H": "Andhra Yuvathi Mandali School of Pharmacy for Women",
    "T8": "Annamacharya Institute of Technology & Sciences",
    "New": "Annie Besant Post Graduate College (MCA)",
    "PP": "AnuBose Institute of Technology",
    "PQ": "Anurag College of Engineering",
    "H6": "Anurag Group of Instituions",
    "30": "Anwarul Uloom College Of Engineering And Technology",
    "80": "Arkay College of Engineering & Technology",
    "PR": "Aryabhata Institute of Technology & Science",
    "62": "Aurora's Engineering College",
    "M9": "Aurora's Scientific &Technological Institute",
    "84": "Aurora's Technological and Research Institute",
    "W7": "Aurora’s Seethaiah Engineering College",
    "H3": "Ayaan College Of Engineering and Tech",
    "5W": "Azad College of Engineering for Women",
    "T6": "Azad College of Pharmacy",
    "21": "B.V.Raju Institute of Technology",
    "AN": "BALAJI INSTITUTE OF ENGINEERING & SCIENCES",
    "C3": "BALAJI INSTITUTE OF TECHNOLOGY & SCIENCE",
    "M1": "BANDARI SRINIVAS INSTITUTE OF TECHNOLOGY",
    "7P": "BASAVARAJU KRISHNA BAI (LAXMI) EDUCATIONAL SOCIETY GROUP OF INSTITUTIONS",
    "17": "BHARAT INSTITUTE OF TECHNOLOGY",
    "CE": "BHARAT SCHOOL OF PHARMACY",
    "GE": "BHASKAR ENGINEERING COLLEGE",
    "EF": "BHASKAR PHARMACY COLLEGE",
    "7Q": "BRILLIANT GRAMMAR SCHOOL EDUCATIONAL SOCIETY'S GROUP OF INSTITUTIONS",
    "QA": "BRILLIANT INSTITUTE OF ENGINEERING & TECHNOLOGY",
    "WH": "BVRIT Hyderabad College of Engineering for women",
    "8C": "Balaji Institute of Management Sciences",
    "8Q": "Bandari Srinivas College of Engineering & Technology",
    "13": "Bharat Engineering College",
    "PU": "Bharat Institute of Technology and Science for Women",
    "E1": "Bharat Institute of\\xa0 Engineering and Technology",
    "32": "Bhoj Reddy Engineering College for Women",
    "Z3": "Bojjam Narasimhulu Pharmacy College for Women",
    "2C": "Bomma Institute of Informatics",
    "9D": "Bomma Institute of Pharmacy",
    "U3": "Bomma Institute of Technology And Science",
    "AQ": "CHILKUR BALAJI INSTITUTE OF TECHNOLOGY",
    "68": "CHRISTU JYOTHI \\xa0INSTITUTE \\xa0OF \\xa0TECHNOLOGY & SCIENCE",
    "8D": "CM School of Business Management",
    "H5": "CMR College of Engineering &Technology",
    "T2": "CMR College of Pharmacy",
    "8R": "CMR ENGINEERING COLLEGE",
    "R0": "CMR Institute of Technology",
    "7R": "CMR TECHNICAL CAMPUS",
    "QC": "CRV INSTITUTE OF TECHNOLOGY & SCIENCE",
    "XU": "CSI WESLEY INSTITUTE OF TECHNOLOGY AND SCIENCES",
    "7J": "CVM  COLLEGE OF PHARMCAY",
    "B8": "CVR College of Engineering",
    "1A": "Chaitanya College of Pharmacy Education & Research",
    "VQ": "Chilkur Balaji College of Computer Sciences",
    "GD": "Chilkur Balaji College of Pharmacy",
    "8T": "Cyberabad Institute of Technology",
    "VR": "D.V.R Post Graduate Institute of Computer Applications",
    "VT": "D.V.R Post Graduate Institute of Management Studies",
    "40": "D.V.R.College of Engineering and Technology",
    "EQ": "DEEVENA COLLEGE OF PHARMACY",
    "EU": "DHANVANTHARI INSTITUTE OF PHARMACEUTICAL SCIENCES",
    "U5": "DRK College of Engineering and Technology",
    "N7": "DRK INSTITUTE OF SCIENCE & TECHNOLOGY",
    "HD": "Daripally Anantha Ramulu College of Engineering & Technology",
    "46": "Deccan School of Pharmacy",
    "1C": "Dhanvanthri College of Pharmaceutical Sciences",
    "TA": "Dhruva Institute of Engineering and Technology",
    "37": "Dr Paul Raj Engineering College",
    "92": "Dr. V.R.K. College of Engineering & Technology",
    "H8": "Dr.V.R.K Women's College of Engineering & Technology",
    "C7": "ELLENKI COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "5Y": "ELLENKI COLLEGE OF ENGINEERING FOR WOMEN",
    "TT": "ELLENKI ENGINEERING COLLEGE",
    "TU": "ELLENKI INSTITUTE \\xa0OF ENGINEERING AND TECHNOLOGY",
    "5Z": "EVR College of Engineering & Technology",
    "E2": "FARAH INSTITUTE OF TECHNOLOGY",
    "25": "G.Narayanamma institute Technology & Science,  For Women",
    "QD": "GANAPATHY COLLEGE OF ENGINEERING",
    "S5": "GANAPATHY\\xa0ENGINEERINGCOLLEGE",
    "1D": "GANGA PHARMACY COLLEGE",
    "8U": "GAYATHRI INSTITUTE OF TECHNOLOGY & SCIENCES",
    "1E": "GAYATRI INSTITUTE OF PHARMACEUTICAL SCINECES AND RESEARCH CENTRE",
    "QF": "GEETANJALI INSTITUTE OF SCIENCE AND TECHNOLOGY",
    "Z5": "GEETHANJALI COLLEGE OF PHARMACY",
    "Z6": "GLOBAL COLLEGE OF PHARMACY",
    "AU": "GNYANA SARASWATI COLLEGE OF  ENGINEERING &  TECHNOLONY",
    "QG": "GOPAL REDDY COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "QE": "Gandhi Academy of Technical Education",
    "R1": "Geetanjali College of Engineering and Technology",
    "7L": "Gland Institute of Pharmaceutical Sciences",
    "9J": "Global Group of Institutions",
    "U6": "Global Institute Of Engineering & Technology",
    "24": "Gokaraju Rangaraju Institute of Engineering & Technology",
    "J0": "Green Fort Engineering College",
    "GQ": "Gurram Bala Narasaiah Institute of Pharmacy",
    "B9": "Guru Nanak Engineering College",
    "8W": "Guru Nanak Institute of Engineering & Technology",
    "1U": "Guru Nanak Institute of P.G.Studies (MBA)",
    "1T": "Guru Nanak Institute of P.G.Studies (MCA)",
    "83": "Guru Nanak Institute of Technology",
    "WJ": "Guru Nanak Institutions Technical Campus",
    "7T": "Gurukul Group of Institutions",
    "Y8": "Gurunanak Institute of Pharmacy",
    "Z8": "Gyana Jyothi College of pharmacy",
    "9L": "Harshith Group of Institutions",
    "U0": "Hasvita Institute of Engineering and Technology",
    "6A": "Hasvita Institute of Management and Technology",
    "8X": "Hasvita Institute of Science and Technology",
    "D8": "Hi Point College of Engineering & Technology",
    "VU": "Holy Mary Institute of Management Studies",
    "QH": "Holy Mary Institute of Technology",
    "C9": "Holy Mary Institute of Technology & Science",
    "S7": "Holy Mary Institute of Technology & Science (College of Pharmacy)",
    "VW": "Holy Mary Institute of Technology & Science (MCA)",
    "7K": "Horizon College Of Pharmacy",
    "E5": "Hyderabad Institute of Technology and Management",
    "VX": "ICON INSTITUTE OF MANAGEMENT STUDIES",
    "WT": "IMMANUEL BUSINESS SCHOOL",
    "D3": "INDUR INSTITUTE OF ENGINEERING & TECHNOLOGY",
    "95": "INSTITUTE OF AERONAUTICAL ENGINEERING",
    "VY": "J.B Institute of Engineering & Technology (MBA)",
    "67": "J.B.INSTITUTE OF ENGINEERING & TECHNOLOGY",
    "BA": "JAWAHARLAL NEHRU INSTITUTE OF TECHNOLOGY",
    "7U": "JAYA PRAKASH NARAYAN EDUCATINAL SOCIETY GROUP OF INSTITUTIONS",
    "DP": "JAYAMUKHI INSTITUTE OF PHARMACEUTICAL\\xa0 SCIENCES",
    "C4": "JAYAMUKHI INSTITUTE OF TECHNOLOGICAL SCIENCES",
    "8E": "JESUS PG COLLEGE",
    "S8": "JJ COLLEGE OF PHARMACY",
    "QJ": "JJ INSTITUTE OF INFORMATION TECHNOLOGY",
    "RD": "JOGINPALLY M N RAO WOMEN’S ENGINEERING COLLEGE",
    "Z2": "JYOTHISHMATHI INSTITUTE OF PHARMACEUTICAL SCIENCES",
    "27": "JYOTHISHMATHI INSTITUTE OF TECHNOLOGY & SCIENCE",
    "36": "Jayaprakash Narayan College of Engineering",
    "DQ": "Joginpally B.R Pharmacy college",
    "J2": "Joginpally B.R. Engineering College",
    "N4": "Jyothishmathi College of Engineering & Technology",
    "EG": "Jyothishmathi College of Pharmacy",
    "QK": "Jyothishmathi Institute of Technological Sciences",
    "9U": "KAKATIYA INSTITUTE OF MANAGEMENT STUDIES",
    "8Y": "KAMAKSHI COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "5D": "KASIREDDY NARAYAN REDDY COLLEGE OF ENGINEERING & RESEARCH",
    "QN": "KBR Engineering College",
    "QM": "KG REDDY COLLEGE OF ENGINEERING & TECHNOLOGY",
    "J3": "KHADER MEMORIAL COLLEGE OF ENGINEERING & TECHNOLOGY",
    "QP": "KHAMMAM INSTITUTE OF TECHNOLOGY & SCIENCES",
    "QQ": "KITE College of Professional Engineering Sciences",
    "QR": "KITE Womens College of Professional Engg Sciences",
    "QT": "KLR College Of Engineering &Technology",
    "8Z": "KLR Engineering College",
    "QU": "KODADA INSTITUTE OF TECHNOLOGY & SCIENCE FOR WOMEN",
    "Y2": "KOTTAM INSTITUTE OF PHARMACY",
    "BE": "KRISHNA MURTHY INSTITUTE OF TECHNOLOGY &  ENGINEERING",
    "X7": "KSRAJU INSTITUTE OF TECHNOLOGY AND SCIENCES",
    "Z9": "KVK COLLEGE OF PHARMACY",
    "XB": "KYASA INSTITUTE OF MANAGEMENT STUDIES",
    "9W": "Kakatiya Institute of Management Studies (MCA)",
    "6B": "Kakatiya Institute of Technonolgy and Science for Women",
    "28": "Kamala Institute of Technology & Science",
    "WU": "Kavitha Memorial PG College (MBA)",
    "WV": "Kavitha Memorial PG College (MCA)",
    "BD": "Keshav Memorial Institute of Technology",
    "RA": "Kommuri Pratap Reddy Institute of Technology",
    "8F": "Kottam Institute of Advanced Studies",
    "5J": "Kottam Institute of P.G. Studies",
    "B4": "Kshatriya College of Engineering",
    "M2": "LORDS INSTITUE OF ENGINEERING AND TECHNOLOGY",
    "WK": "LUMBINI GROUP OF INSTITUTIONS",
    "9N": "Lakshya Institute of Management",
    "9F": "Lalitha College of Pharmacy",
    "ww": "Laqshya College of Management",
    "RC": "Laqshya Institute of  Technology & Sciences",
    "9T": "Lotus Institute of Management Studies MBA",
    "VH": "M A K College of Pharmacy",
    "WX": "M. C. GUPTA COLLEGE OF BUSINESS MANAGEMENT",
    "CC": "M.R.R College of B. Pharmacy",
    "82": "MAHESHWARA ENGINEERING COLLEGE",
    "FC": "MAHESHWARA INSTITUTE OF PHARMACY",
    "RG": "MALLA REDDY COLLEGE OF ENGINEERING FOR WOMEN",
    "RJ": "MALLA REDDY INSTITUTE OF TECHNOLOGY",
    "HF": "MALLA REDDY PHARMACY COLLEGE [Formerly CM College of Pharmacy]",
    "7Y": "MARRI LAXMAN REDDY INSTITUTE OF TECHNOLOGY AND MANAGEMENT",
    "J6": "MEDAK COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "RN": "MEDHA COLLEGE OF ENGINEERING",
    "RP": "MEGHA INSTITUTE OF ENGINEERING & TECHNOLOGY FOR WOMEN",
    "5X": "MES Engineering College (Formerly City Womens College of Engineering & Technology )",
    "RQ": "MINA INSTITUTE OF ENGINEERING & TECHNOLOGY FOR WOMEN",
    "R2": "MLR Institute of Technology",
    "RE": "MNR COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "XC": "MOHAMMADIYA INSTITUTE OF MANAGEMENT",
    "6D": "MOHAMMADIYA INSTITUTE OF TECHNOLOGY",
    "CA": "MOONRAY INSTITUTE  OF PHRAMCEUTICAL SCIENCES",
    "C6": "MOTHER TERESA INSTITUTE OF SCIENCE & TECHNOLOGY",
    "7M": "MOTHER TERESA PHARMACY COLLEGE",
    "8L": "MR College of Business Management",
    "1F": "MRM COLLEGE OF PHARMACY",
    "6E": "MUMTAZ COLLEGE OF ENGINEERING & TECHNOLOGY",
    "R5": "MURTHY INSTITUTE OF TECHNOLOGY AND SCIENCE",
    "RF": "Madhira College of Engineering",
    "7X": "Madhira Educational Society Group of Institutions",
    "AE": "Madhira Institute of Technolagy & Science",
    "G7": "Madhira Institute of Technology & Sciences",
    "26": "Mahatma Gandhi Institute of Technology",
    "E3": "Mahaveer Institute of Science & Technology",
    "59": "Maheshwara Institute of Technology",
    "FD": "Maheswara College of Pharmacy",
    "Q9": "Malla Reddy College of Engineering",
    "N3": "Malla Reddy College of Engineering and Technology (Autonomous)",
    "UJ": "Malla Reddy Engineering  College and Management Sciences",
    "RH": "Malla Reddy Engineering College for women",
    "J4": "Malla Reddy Engineering College(Autonomous)",
    "8G": "Malla Reddy Institute of Business Management",
    "8H": "Malla Reddy Institute of Management & Technology",
    "8J": "Malla Reddy Institute of Management Sciences",
    "T3": "Malla Reddy Institute of Pharmaceutical Sciences",
    "S1": "Malla Reddy Institute of Technology & Science",
    "W9": "Malla Reddy Institute of engineering and technology",
    "8K": "Malla Reddy Management College for Women",
    "GF": "Malla Reddy PG College",
    "J5": "Mannan Institute of Science and Technology",
    "BU": "Marri Laxman Reddy Institute of Pharmacy",
    "RM": "Matrix Institute of Technology",
    "WY": "Mohammadiya Institute of Computer Technology",
    "J7": "Mona College of Engineering & Technology",
    "86": "Mother Theressa College of Engineering and Technology",
    "VK": "NALANDA COLLEGE OF PHARMACY",
    "9M": "NARAYANA ENGINEERING & TECHNICAL CAMPUS",
    "TD": "NIGAMA ENGINEERING COLLEGE",
    "E0": "NIZAM INSTITUTE OF ENGINEERING &TECHNOLOGY",
    "S9": "NIZAM INSTITUTE OF PHARMACY",
    "66": "NOOR COLLEGE OF ENGINEERING & TECHNOLOGY",
    "VZ": "NOVA PG COLLEGE",
    "6H": "NRI Institute of Technology",
    "58": "Nagarjuna Institute of Technology & Sciences",
    "RR": "Nalgonda Institute of Technology & science",
    "B6": "Nalla Malla Reddy Engineering Collge",
    "7Z": "Nalla Narasimha Reddy Education Society's Group of Institutions",
    "X0": "Narsimha Reddy Engineering College",
    "8M": "Narsimha Reddy PG College",
    "RT": "Nawab Shah Alam Khan college of Engineering & Technology",
    "N2": "Netaji Institute of Engineering & Technology",
    "CF": "Netaji Institute of Pharmaceutical Sciences",
    "WZ": "Netaji School of Managment",
    "RU": "New India College of Engineering & Technology",
    "TC": "Nexus College of Science & Technology",
    "94": "Nirmal Engineering College",
    "M3": "Nishitha College of Engineering & Technology",
    "5F": "Noble College of Engineering & Technology for Women",
    "CG": "Nova College of Pharmaceutical Education and Research",
    "6G": "Nova Institute of Technological Research for Women",
    "WA": "Nova PG College (MCA)",
    "R3": "Nova\\xa0 College of Engineering & Technology",
    "J8": "P.INDRA REDDY MEMORIAL ENGINEERING COLLEGE",
    "6F": "PALLAVI ENGINEERING COLLEGE",
    "6K": "PATHFINDER ENGINEERING COLLEGE",
    "CH": "PRAGATHI PHARMACY COLLEGE",
    "EJ": "PRASAD INSTITUTE OF PHARMACEUTICAL SCIENCES",
    "GA": "PRINCETON COLLEGE OF PHARMACY",
    "VG": "PRIYADARSHINI INSTITUTE OF SCIENCE & TECH",
    "GR": "PRRM College of Pharmacy",
    "61": "PRRM ENGINEERING COLLEGE",
    "TJ": "PULIPATI PRASAD INSTITUTE OF TECHNOLOGY & SCIENCE",
    "6N": "PULLA REDDY ENGINEERING COLLEGE",
    "TH": "PULLA REDDY INSTITUTE OF TECHNOLOGY",
    "D5": "Pallavi VIF College of Engineering and Technology",
    "6J": "Panineeya Institute of Technology & Science",
    "1G": "Patlolla Ramakrishna Reddy college of pharmacy",
    "RK": "Pragna Bharath Institute of Technology",
    "6L": "Prasad Engineering College",
    "CJ": "Prathap Narender Reddy College of Pharmacy",
    "CK": "Pratishta Institute of Pharmaceutical Sciences",
    "6M": "Princeton Institute Of Engineering And Technology For Women",
    "L7": "Princeton college of Engg. & Tech",
    "6C": "Priyadarshini Institute of Science & Technology for Women",
    "TE": "Prof.Rama Reddy College of Engg & Technology",
    "K0": "Progressive Engineering College",
    "TF": "Pujya Shri MADHAVANJI College of Engineering & Technology",
    "CM": "Pulla Reddy Institute of Pharmacy",
    "Y4": "R.G.R Siddhanthi College of Pharmacy(Co-Education)",
    "D6": "RAJAMAHENDRA COLLEGE OF ENGINEERING",
    "XD": "RATAGN GLOBAL BUSINESS SCHOOL",
    "9X": "RKLK P.G. COLLEGE",
    "9Y": "ROUSSEAU INSTITUTE OF MANAGEMENT STUDIES",
    "M5": "RRS COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "5C": "Ramanandatirtha Engineering College",
    "87": "Ramappa Engineering College",
    "6P": "Rishi Ms Institute Of Engineering & Technology For Women",
    "EN": "Rosory College of Pharmacy",
    "K3": "Royal Institute of Technology And Science",
    "K4": "S R ENGINEERING COLLEGE",
    "VF": "S R International Institute of Technology",
    "GM": "S.P.R. College of Engineering & Technology",
    "E6": "S.R.R Engineering College",
    "R7": "S.S Instt. of Technology",
    "60": "S.S.J ENGINEERING COLLEGE",
    "W4": "S.V. College of Engineering and Technology",
    "6Q": "S.V. Institute of Engineering and Technology",
    "2A": "S.V.College of Computer Sciences",
    "TM": "SAHAJA INSTITUTE OF TECHNOLOGY & SCIENCES For WOMEN",
    "6R": "SAHASRA COLLEGE OF ENGINEERING FOR WOMEN",
    "6T": "SAI - SUDHIR INSTITUTE OF ENGINEERING AND TECHNOLOGY",
    "U1": "SAMSKRUTI COLLEGE OF ENGINEERING & TECHNOLOGY",
    "Y7": "SAMSKRUTI COLLEGE OF PHARMACY",
    "M8": "SANA  Engineering COLLEGE",
    "FT": "SANA COLLEGE OF PHARMACY",
    "GP": "SCIENT INSTITUTE OF PHARMACY",
    "C0": "SCIENT INSTITUTE OF TECHNOLOGY",
    "K7": "SHAAZ COLLEGE OF ENGINEERING & TECHNOLOGY",
    "XF": "SIDDHARTHA INSTITUTE OF PHARMACY0",
    "DT": "SLC'S COLLEGE OF PHARMACY",
    "S3": "SLC'S INSTITUTE OF ENGINEERING & TECHNOLOGY",
    "N8": "SPHOORTHY ENGINEERING COLLEGE",
    "R4": "SPRING FIELDS ENGINEERING COLLEGE",
    "N0": "SREE CHAITANYA COLLEGE OF ENGINEERING",
    "1K": "SREE CHAITANYA INSTITUTE OF PHARMACEUTICAL SCIENCES",
    "TR": "SREE CHAITANYA INSTITUTE OF TECHNOLOGICAL SCIENCES",
    "U2": "SREE DATTHA INSTITUTE OF PHARMACY",
    "C8": "SREEKAVITHA ENGINEERING COLLEGE",
    "UZ": "SREEKAVITHA INSTITUTE OF MANAGEMENT",
    "VE": "SREYAS INSTITUTE OF ENGINEERING AND TECHNOLOGY",
    "D4": "SRI INDU COLLEGE OF ENGINEERING & TECHNOLOGY",
    "T0": "SRI INDU INSTITUTE OF PHARMACY",
    "93": "SRI KOTTAM TULASI REDDY MEMORIAL COLLEGE OF ENGINEERING",
    "X8": "SRI SARADA INSTITUTE OF SCIENCE & TECHNOLOGY",
    "B3": "SRINIVAS REDDY INSTITUTE OF TECHNOLOGY",
    "GU": "SRINIVASA PHARMACEUTICAL INSTITUTE AND CENTRE FOR RESEARCH",
    "VB": "SRM PG COLLEGE (MBA)",
    "VA": "SRM PG COLLEGE(MCA)",
    "WM": "SRR College of Pharmaceutical Sciences",
    "FJ": "SSJ COLLEGE OF PHARMACY",
    "6X": "SUJALA BHARATI INSTITUTE OF TECHNOLOGY",
    "WC": "SUPRABHATH PG COLLEGE",
    "5H": "SURABHI DAYAKAR RAO COLLEGE OF PHARMACY",
    "1J": "SUSHRUT INSTITUTE OF PHARMACY",
    "TK": "SVS Group of Institutions",
    "FM": "SWAMI RAMANANDA TIRTHA INSTITUTE OF PHARMACEUTICAL SCIENCES",
    "FU": "SWAMI VIVEKANANDA INSTITUTE OF PHARMACEUTICAL SCIENCES",
    "M6": "SWRNA BHARATHI INSTITUTE OF SCIENCE AND TECHNOLOGY",
    "7B": "Sagar Group of Institutions, Sagar Institute of Technology",
    "9Z": "Sahaja School of Business",
    "FA": "Sai Pranavi College of Pharmacy",
    "C5": "Sai Spurthi Institute of Technology",
    "8N": "Samskruthi Faculty of Business Management",
    "TN": "Sana College of Engineering Technology & Research Institute",
    "U8": "Sarada Institute of Technology & Science",
    "EE": "Saraswathi College Of Pharmaceutical Sciences",
    "08": "Shadan College of Engineering and Technology",
    "11": "Shadan College of Pharmacy",
    "L5": "Shadan Womens College of Engineering & Technology",
    "41": "Shadan Womens College of Pharmacy",
    "M4": "Shahjehan College of Engg. & Tech",
    "1H": "Shantha Institute of Pharmaceutical Sciences",
    "TP": "Siddhartha Institute of Engineering & Technology",
    "TQ": "Siddhartha Institute of Technology & Sciences",
    "B7": "Sindhura College Of Engineering & Technology",
    "XE": "Singareni Collieries Women’s College",
    "CT": "Sitha Institute of Pharmaceutical Science",
    "1R": "Sree Chaitanya Institute of Management & Computer Sciences",
    "UX": "Sree Chaitanya P.G. College (MBA Programme)",
    "UW": "Sree Chaitanya P.G. College (MCA)",
    "9P": "Sree Dattha Group of Institutions",
    "E4": "Sree Dattha Institute of Engineering and Science",
    "UY": "Sree Dattha School of Business Management",
    "FR": "Sree Nagarjuna College of Pharmacy",
    "x6": "Sree Rama Institute of Thecnology & Science",
    "9A": "Sree Vaanmayi Institute of Engineering and Technology",
    "57": "Sree Visvesvaraya Institute of Technology & Science",
    "6U": "SreeKavitha Institute of Science and Technology",
    "31": "Sreenidhi Institute of Science & Technology",
    "8A": "Sri Chaitanya Technical Campus",
    "X3": "Sri Indu Institute of Engineering & Technology",
    "6W": "Sri Nagoji Rao Institute of Technology and Science (Women)",
    "8B": "Sri Sai Educational Society’s Group of Institutions",
    "CU": "Sri Sarada College of Pharmacy",
    "63": "Sri Venkateswara Engineering College",
    "D7": "Sri YPR \\xa0College of Engineering and Technology",
    "B5": "Srinivasa Engineering College",
    "XP": "St. John College of Pharmacy",
    "XM": "St. John MBA College",
    "K8": "St. Martin's Engineering College",
    "BH": "St. Mary's Engineering College",
    "D0": "St. Mary's Group of Institutions Hyderabad",
    "7W": "St. Mary’s Integrated Campus Hydedrabad",
    "BK": "St. PETER'S ENGINEERING COLLEGE",
    "FP": "St. Peter's College of Pharmacy",
    "XN": "St.John PG College",
    "XK": "St.John School of Management",
    "DE": "St.Mary’s College of Pharmacy",
    "DF": "St.Mary’s Pharmacy College",
    "WB": "St.Mary’s School of Business Management",
    "1M": "St.Peter’s Institute of Pharmaceutical Education & Research",
    "UA": "Sudheer Reddy College of engineering & technology For Women",
    "45": "Sultan-ul-Uloom College of Pharmacy",
    "6Y": "Sumathi Reddy Institute of Technology for Women",
    "7A": "Supraja Institute of Technology and Sciences",
    "14": "Swami Ramananda Tirtha Institute of Science & Technology",
    "P7": "Swami Vivekananada Institue of Technology",
    "W0": "Swarna Bharathi College of Engineering",
    "WD": "Swarna Bharathi Institute of Management and Science (SBIM)",
    "56": "Syed Hashim College of Science And Technology",
    "7C": "Symbiosis Institute of Technology & Science",
    "R9": "TEEGALA KRISHNA REDDY ENGINEERING COLLEGE",
    "ET": "TEJA COLLEGE OF PHAMACY",
    "K9": "TKR College of Engineering & Technology",
    "UE": "TRINITY COLLEGE OF ENGINEERING & TECHNOLOGY",
    "UD": "TRINITY COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "XA": "TRINITY PG COLLEGE",
    "L0": "TRR  COLLEGE of ENGINEERING",
    "UF": "TRR College of Engineering & Technology",
    "1P": "TRR College of Pharmacy",
    "D1": "TRR Engineering College",
    "7D": "TRR Engineering College for Women",
    "9B": "TRV College of Engineering & Technology",
    "5E": "TUDI NARASIMHA REDDY  INSTITUTE OF TECHNOLOGY & SCIENCES",
    "UG": "TUDI RAM REDDY INSTITUTE OF TECHNOLOGY & SCIENCES",
    "5A": "TURBOMACHINERY INSTITUTE OF TECHNOLOGY AND SCIENCES",
    "UC": "Talla Padmavathi College of Engineering",
    "FQ": "Talla Padmavathi Pharmacy College",
    "DG": "Teegala Krishna Reddy College of Pharmacy",
    "AD": "Teegala Ram Reddy College of Pharmacy",
    "P0": "The Younis Sultan College of Engg",
    "1N": "Tirumala College of Pharmacy",
    "WL": "Tirumala College of Pharmacy(Integrated Campus)",
    "C2": "Tirumala Engineering College",
    "5P": "Tudi Narasimha Reddy Institute of Technology & Sciences",
    "5K": "Turbo Machinery Institute of Technology & Sciences",
    "VJ": "UNITY COLLEGE OF PHARMACY",
    "WE": "UNITY P.G. COLLEGE",
    "VC": "USHODAYA INSTITUTE OF MANAGEMENT & TECHNOLOGY",
    "64": "VAAGDEVI COLLEGE OF ENGINEERING",
    "UK": "VAAGDEVI ENGINEERING COLLEGE",
    "ED": "VAAGDEVI PHARMACY COLLEGE",
    "2E": "VAAGESWARI  INSTITUTE OF MANAGEMENT SCIENCES",
    "S4": "VAAGESWARI COLLEGE OF ENGINEERING",
    "UN": "VARADHA REDDY COLLEGE OF ENGINEERING",
    "AA": "VATHSALYA COLLEGE OF PHARMACY",
    "E7": "VATHSALYA INSTITUTE OF SCIENCE AND TECHNOLOGY",
    "EP": "VENKATESHWARA INSTITUTE OF PHARMACEUTICAL SCIENCES",
    "9C": "VIDYA VIKAS ENGINEERING COLLEGE",
    "Y5": "VIGNAN INSTITUTE OF PHARMACEUTICAL SCIENCES",
    "89": "VIGNAN INSTITUTE OF TECHNOLOGY & SCIENCE",
    "P8": "VIGNANA BHARATHI ENGINEERING COLLEGE",
    "UP": "VIGNAN’S INSTITUTE OF MANAGEMENT AND TECHNOLOGY FOR WOMEN",
    "N5": "VIJAY INSTITUTE OF TECHNOLOGY AND SCIENCE",
    "BR": "VIJAYA ENGINEERING COLLEGE",
    "WR": "VIJAYA INSTITUTE OF MANAGEMENT",
    "WG": "VIKAS COLLEGE OF PHARMACY",
    "UT": "VISHNUSREE INSTITUTE OF TECHNOLOGY",
    "HA": "VISION COLLEGE OF PHARMACEUTICAL SCIENCES & RESEARCH",
    "BT": "VISVESVARAYA COLLEGE OF ENGINEERING & TECHNOLOGY",
    "7G": "VITS Women’s Engineering College",
    "UH": "VIVEKANANDA INSTITUTE OF SCIENCE & INFORMATION TECHNOLOGY",
    "N9": "VIVEKANANDA INSTITUTE OF TECHNOLOGY & SCIENCE (N9)",
    "W1": "VIVEKANANDA INSTUTE OF ENGINEERING & TECHNOLOGY",
    "07": "VNR Vignana Jyothi Institute of Engineering & Technology",
    "WN": "Vaageswari College of Pharmacy",
    "UM": "Vaageswari Engineering College",
    "2D": "Vaageswari Institute of Computer Sciences",
    "EC": "Vaageswari Institute of Pharmaceutical Sciences,",
    "88": "Vardhaman College of Engineering",
    "J9": "Vidya Bharathi Institute of Technology",
    "91": "Vidya Jyothi  Institute of Technology",
    "P6": "Vignana Bharathi Institute of Technology",
    "UQ": "Vignan’s Institute of Technology & Aeronautical Engineering",
    "9E": "Vijay College of Pharmacy",
    "29": "Vijay Rural Engineering College",
    "7E": "Vijay college of Engineering for Women",
    "Y6": "Vijaya College of pharmacy",
    "UR": "Vijaya krishna Institute of Technology and Science",
    "VM": "Vikas College of Pharmaceutical Sciences",
    "DH": "Vishnu Institute of Pharmaceutical Education & Research",
    "UU": "Vishwa Bharathi College of Engineering",
    "7F": "Vishwa Bharathi Institute of Technology And Sciences",
    "WF": "Vishwa Bharathi PG College of Engineering & Management",
    "XG": "Vishwa Bharathi PG College of Engineering & Management",
    "9R": "Vivekananda Group of Institutions",
    "N6": "Vivekananda Institute of Technology & Science",
    "d2": "Sridevi women's engineering college",
    "W7": "St. Mary’s College of Engineering & Technology",
}
export default colleges